version: '3.8'
services:
  zkksp-prover-angular:
    image: zkksp-prover-angular
    ports:
      - '8082:3332'
  zkksp-prover-backend:
    image: zkksp-prover-backend
    ports:
      - '8083:3333'
#  zkksp-verifier-backend:
#    image: zkksp-verifier-backend
#    environment:
#      - apiPath=http://api:3333
#    ports:
#      - '8084:3334'
