version: '3.8'
services:
  zkksp-prover-angular:
    image: zkksp-prover-angular
    ports:
      - '8082:3332'
  zkksp-prover-backend:
    image: zkksp-prover-backend
    ports:
      - '8083:3333'
    networks:
      - open-network
  zkksp-verifier-backend:
    depends_on:
      - dynamodb
    image: zkksp-verifier-backend
    ports:
      - '8084:3334'
    hostname: verifier
    networks:
      - dynamodb-network
      - open-network
  dynamodb:
    image: amazon/dynamodb-local
    container_name: svscribe-dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    ports:
      - '8000:8000'
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/ -port 8000"
    networks:
      - dynamodb-network
networks:
  dynamodb-network:
    driver: bridge
  open-network:
    driver: bridge
